### ISSUE TITLE
Panic in `kiss_xml::parse_str`

### ISSUE THREAD

**Issue by rfuzz** [DrPlantabyte/kiss-xml#21]
Hello, during fuzz testing of the current crate, I discovered input data that causes the `kiss_xml::parse_str` function to panic (an unclosed tag containing an `=` character):

```rust
fn main() {
    let xml = r#"
<property =
<property />
"#;
    match kiss_xml::parse_str(xml) {
        Ok(dom) => {
            println!("OK");
        }
        Err(e) => {
            println!("Error: {:?}", e);
        }
    };
}
```

Upon running the code, the following panic occurs:

```shell
thread 'main' panicked at /home/ubuntu/kiss-xml/src/lib.rs:626:19:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_const::panic_const_sub_overflow
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/panicking.rs:181:21
   3: kiss_xml::parse_new_element
             at /home/ubuntu/kiss-xml/src/lib.rs:626:13
   4: kiss_xml::parse_str
             at /home/ubuntu/kiss-xml/src/lib.rs:453:35
   5: kiss_xml_fuzz_target_test::main
             at ./src/main.rs:6:11
   6: core::ops::function::FnOnce::call_once
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

version: `commit 8f564485147191d4b9087b9fa7d0acc404221fca`

**Comment by DrPlantabyte** [comment]
Thank you very much for bringing this to my attention. I'll publish a fix soon

**Comment by DrPlantabyte** [comment]
Fixed in https://github.com/DrPlantabyte/kiss-xml/pull/23
